import request from '@/service/fetch';

export const register = (params: any, config = {}) => request.post('/api/user/register', params, config)
export const login = (params: any, config = {}) => request.post('/api/user/login', params, config)
export const logout = (params: any = {}, config = {}) => request.post('/api/user/logout', params, config)
export const userUpdate = (params: any = {}, config = {}) => request.post('/api/user/update', params, config)
export const userDelete = (params: any = {}, config = {}) => request.post('/api/admin/user/delete', params, config)
export const getAdminUserList = (params: any = {}, config = {}) => request.post('/api/admin/user/list', params, config)
export const getLinkList = (params: any = {}, config = {}) => request.post('/api/link/list', params, config)
export const getCardList = (params: any = {}, config = {}) => request.post('/api/card/list', params, config)
export const getAdminCardList = (params: any = {}, config = {}) => request.post('/api/admin/card/list', params, config)
export const getAdminUserCardList = (params: any = {}, config = {}) => request.post('/api/admin/user/card/list', params, config)
export const getUserLinkList = (params: any = {}, config = {}) => request.post('/api/user/link/list', params, config)
export const getAdminUserLinkList = (params: any = {}, config = {}) => request.post('/api/admin/user/link/list', params, config)
export const getUserCardList = (params: any = {}, config = {}) => request.post('/api/user/card/list', params, config)
export const getClassList = (params: any = {}, config = {}) => request.post('/api/class/list', params, config)
export const classAdd = (params: any = {}, config = {}) => request.post('/api/class/add', params, config)
export const classDel = (params: any = {}, config = {}) => request.post('/api/class/del', params, config)
export const classUpdate = (params: any = {}, config = {}) => request.post('/api/class/update', params, config)
export const linkDel = (params: any = {}, config = {}) => request.post('/api/link/del', params, config)
export const linkAdd = (params: any = {}, config = {}) => request.post('/api/link/add', params, config)
export const linkUpdate = (params: any = {}, config = {}) => request.post('/api/link/update', params, config)
export const cardDel = (params: any = {}, config = {}) => request.post('/api/card/del', params, config)
export const cardAdd = (params: any = {}, config = {}) => request.post('/api/card/add', params, config)
export const cardUpdate = (params: any = {}, config = {}) => request.post('/api/card/update', params, config)
export const userLinkDel = (params: any = {}, config = {}) => request.post('/api/user/link/del', params, config)
export const userLinkAdd = (params: any = {}, config = {}) => request.post('/api/user/link/add', params, config)
export const userLinkUpdate = (params: any = {}, config = {}) => request.post('/api/user/link/update', params, config)
export const userCardDel = (params: any = {}, config = {}) => request.post('/api/user/card/del', params, config)
export const userCardAdd = (params: any = {}, config = {}) => request.post('/api/user/card/add', params, config)
export const userCardUpdate = (params: any = {}, config = {}) => request.post('/api/user/card/update', params, config)
export const applyContribute = (params: any = {}, config = {}) => request.post('/api/contribute/apply', params, config)
export const getContributeList = (params: any = {}, config = {}) => request.post('/api/admin/contribute/list', params, config)
export const contributeDelete = (params: any = {}, config = {}) => request.post('/api/admin/contribute/del', params, config)
export const contributeUpdate = (params: any = {}, config = {}) => request.post('/api/admin/contribute/update', params, config)
export const adminLogin = (params: any = {}, config = {}) => request.post('/api/user/verify', params, config)
export const adminUserUpdate = (params: any = {}, config = {}) => request.post('/api/admin/user/update', params, config)
export const getPublicKey = (params: any = {}, config = {}) => request.post('/api/user/public/key', params, config)
export const getAdminLogsList = (params: any = {}, config = {}) => request.post('/api/adminLogs/list', params, config)
export const getAdminPermissionList = (params: any = {}, config = {}) => request.post('/api/permission/list', params, config)
export const getAdminRoleList = (params: any = {}, config = {}) => request.post('/api/role/list', params, config)
export const getAdminList = (params: any = {}, config = {}) => request.post('/api/root/list', params, config)
